### ISSUE TITLE
Strange plots resorting from different usage of q2-longitudinal

### ISSUE THREAD

**Issue by shiffer1** [qiime2/q2-longitudinal#84] opened 2018-03-28 22:02 UTC
Hello, 
I am using q2-longitudinal in a bit of a different way than it was originally perceived for and some strange  behavior has resulted. This issue has arisen in creating a volatility plot using this code:
qiime longitudinal volatility \
  --m-metadata-file ../EXMP_Sample_metadata_3_17_2018.tsv \
  --m-metadata-file EXMP-200-4562-single-core-metrics-results/shannon_vector.qza \
  --p-metric shannon \
  --p-group-column activity \
  --p-state-column sample_number \
  --p-individual-id-column redcap_survey_identifier \
  --p-spaghetti yes \
  --o-visualization EXMP-200-4562-single-shannon-volatility.qzv 
I am introducing an intervention period to be compared to a baseline period both prior to and after the intervention. As you can see this creates a volatility plot that is unusual:
![image](https://user-images.githubusercontent.com/10201170/38058706-a2d1b558-3298-11e8-87c6-0c0eb00b6d9d.png)
![image](https://user-images.githubusercontent.com/10201170/38058753-d5c84c06-3298-11e8-98e0-d03e56abb1c4.png)
![image](https://user-images.githubusercontent.com/10201170/38058770-e04f4986-3298-11e8-8fa2-a7879ce82295.png)

It causes some strange behavior that I am not so sure is a bug, but rather arising from the differing way I am trying to do things. 
Thanks,
Arron Shiffer

**Comment by nbokulich** [comment] 2018-04-02 17:12
@shiffer1 and I discussed off-line. This issue is indeed caused by unusual use of this method. The `group-column` is specifying a metadata column that partitions groups by time, and hence these "groups" are not actually sampled at the same time periods. This causes problems for plotting and comparing temporal differences between these "groups" since they are in fact the same individuals but sampled at different intervention periods.

It would be ideal to raise an error when this occurs, but I am not sure there is a good catch-all since this will depend largely on individual characteristics of the data and user choices.

So I will close this for now — unless if we find a bug related to this issue.

**Closed as completed by nbokulich** 2018-04-02 17:12 UTC
